<script setup lang="ts">
import { withBase } from 'vitepress'

// VitePress replaces a *.data.ts loader's default export with this named
// client-side data export during the documentation build.
// @ts-expect-error generated by the VitePress data-loader transform
import { data as posts } from '../../../blog/posts.data.mts'

const dateFormatter = new Intl.DateTimeFormat('en-US', {
  dateStyle: 'long',
  timeZone: 'UTC',
})

function formatDate(date: string): string {
  return dateFormatter.format(new Date(`${date}T00:00:00Z`))
}
</script>

<template>
  <div v-if="posts.length" class="blog-index">
    <article v-for="post in posts" :key="post.url" class="blog-index-entry">
      <div class="blog-index-meta">
        <span class="blog-index-category">{{ post.category }}</span>
        <time :datetime="post.date">{{ formatDate(post.date) }}</time>
      </div>
      <h2>
        <a :href="withBase(post.url)">{{ post.title }}</a>
      </h2>
      <p>{{ post.description }}</p>
      <div v-if="post.tags.length" class="blog-index-tags">
        <span v-for="tag in post.tags" :key="tag">{{ tag }}</span>
      </div>
    </article>
  </div>
  <p v-else class="blog-index-empty">No posts have been published yet.</p>
</template>

<style scoped>
.blog-index {
  display: grid;
  gap: 18px;
  margin-top: 28px;
}

.blog-index-entry {
  padding: 24px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  background: var(--vp-c-bg-soft);
}

.blog-index-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 12px;
  align-items: center;
  color: var(--vp-c-text-2);
  font-size: 13px;
}

.blog-index-category {
  color: var(--vp-c-brand-1);
  font-weight: 650;
  letter-spacing: 0.02em;
  text-transform: uppercase;
}

.blog-index-entry h2 {
  margin: 12px 0 8px;
  border: 0;
  line-height: 1.2;
}

.blog-index-entry h2 a {
  color: var(--vp-c-text-1);
  text-decoration: none;
}

.blog-index-entry h2 a:hover {
  color: var(--vp-c-brand-1);
}

.blog-index-entry p {
  margin: 0;
  color: var(--vp-c-text-2);
}

.blog-index-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 16px;
}

.blog-index-tags span {
  padding: 3px 8px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 999px;
  color: var(--vp-c-text-2);
  font-size: 12px;
}

.blog-index-empty {
  margin-top: 28px;
  color: var(--vp-c-text-2);
}

@media (max-width: 640px) {
  .blog-index-entry {
    padding: 20px;
  }
}
</style>
