"""Logical value identities and storage specifications for residency management.

This module defines tensor-free handles, immutable specifications, and the
synchronous reconstruction requirements used by ``ResidencyManager`` to validate
managed values, replica behavior, recoverability, and storage charges.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Generic, Protocol, TypeVar

from fhelium.core import TensorResident

ValueT_co = TypeVar("ValueT_co", bound=TensorResident, covariant=True)


class ReplicaMode(StrEnum):
    """Constraint on simultaneous materializations of one managed value."""

    REPLICABLE = "replicable"
    EXCLUSIVE = "exclusive"


class Recoverability(StrEnum):
    """Whether a managed value may lose its final materialization."""

    RECONSTRUCTIBLE = "reconstructible"
    MUST_PRESERVE = "must-preserve"


def _require_nonempty_string(value: object, *, field_name: str) -> None:
    if not isinstance(value, str):
        raise TypeError(f"{field_name} must be a string")
    if not value.strip():
        raise ValueError(f"{field_name} must be non-empty")


def _require_nonnegative_int(value: object, *, field_name: str) -> None:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{field_name} must be an integer, not bool")
    if value < 0:
        raise ValueError(f"{field_name} must be non-negative")


def _require_value_type(value_type: object, *, field_name: str) -> None:
    if not isinstance(value_type, type) or not issubclass(
        value_type, TensorResident
    ):
        raise TypeError(f"{field_name} must be a TensorResident class")


@dataclass(frozen=True, slots=True)
class ResidencyHandle(Generic[ValueT_co]):
    """Manager-issued tensor-free identity of one typed managed value.

    Handles are immutable and hashable, and therefore remain valid dictionary
    keys independently of every materialization's device and lifetime.  The
    ``value_type`` field preserves the expected runtime class without retaining
    a tensor-bearing value. ``manager_id`` prevents accidental cross-manager
    use, while ``handle_id`` is an opaque identity generated for each
    :meth:`ResidencyManager.adopt` or
    :meth:`ResidencyManager.register_source` call. Moving, copying, or dropping
    a materialization does not change the handle.

    Args:
        manager_id: Non-empty identity of the manager that issued the handle.
        handle_id: Non-empty opaque identity generated by the manager.
        value_type: Expected concrete or base ``TensorResident`` runtime class.
    """

    manager_id: str
    handle_id: str
    value_type: type[ValueT_co]

    def __post_init__(self) -> None:
        _require_nonempty_string(
            self.manager_id,
            field_name="ResidencyHandle manager_id",
        )
        _require_nonempty_string(
            self.handle_id,
            field_name="ResidencyHandle handle_id",
        )
        _require_value_type(
            self.value_type,
            field_name="ResidencyHandle value_type",
        )


@dataclass(frozen=True, slots=True)
class ResidencyValueSpec(Generic[ValueT_co]):
    """Immutable storage specification for one managed value.

    ``logical_nbytes`` is the value's tensor payload size, while
    ``storage_nbytes`` is the fixed conservative charge used for each physical
    residency admission. A moved view may use less actual backing storage but
    may not exceed this registered ceiling; accounting still debits the full
    charge.
    This model requires the storage charge to be at least the logical payload
    size.  Implementations with overlapping tensor views must therefore charge
    the full logical extent rather than deduct shared backing storage; this
    conservative rule makes admission accounting independent of alias analysis.

    Args:
        value_type: Expected ``TensorResident`` runtime class.
        logical_nbytes: Non-negative logical tensor payload bytes.
        storage_nbytes: Non-negative physical residency charge, greater than or
            equal to ``logical_nbytes``.
        replica_mode: Whether simultaneous replicas are permitted.
        recoverability: Whether the final materialization may be discarded.
    """

    value_type: type[ValueT_co]
    logical_nbytes: int
    storage_nbytes: int
    replica_mode: ReplicaMode
    recoverability: Recoverability

    def __post_init__(self) -> None:
        _require_value_type(
            self.value_type,
            field_name="ResidencyValueSpec value_type",
        )
        _require_nonnegative_int(
            self.logical_nbytes,
            field_name="ResidencyValueSpec logical_nbytes",
        )
        _require_nonnegative_int(
            self.storage_nbytes,
            field_name="ResidencyValueSpec storage_nbytes",
        )
        if self.storage_nbytes < self.logical_nbytes:
            raise ValueError(
                "ResidencyValueSpec storage_nbytes must be greater than or "
                "equal to logical_nbytes"
            )
        if not isinstance(self.replica_mode, ReplicaMode):
            raise TypeError(
                "ResidencyValueSpec replica_mode must be a ReplicaMode"
            )
        if not isinstance(self.recoverability, Recoverability):
            raise TypeError(
                "ResidencyValueSpec recoverability must be a Recoverability"
            )


class ResidencySource(Protocol[ValueT_co]):
    """Synchronous reconstruction source for one managed value.

    Sources are registered directly with residency state and return a ready
    ``TensorResident`` value when invoked. The manager validates its runtime
    type, byte accounting, and initial location. The source is trusted to
    return the contents and CKKS state registered for that handle; the
    source owns content-identity correctness. Each call must return independent
    tensor storage whose logical alias ownership transfers to the manager; a
    source must not retain or later mutate the returned materialization.
    """

    def load(self) -> ValueT_co:
        """Synchronously reconstruct and return the registered value."""

        ...


__all__ = [
    "Recoverability",
    "ReplicaMode",
    "ResidencyHandle",
    "ResidencySource",
    "ResidencyValueSpec",
]
