# This file is generated by scripts/generate_native_wrappers.py.
# Do not edit!

from __future__ import annotations

import torch


def _require_native() -> None:
    from fhelium.native import require_native

    require_native()


def add_contiguous_compressed_plaintext_component(
    ciphertext_component: torch.Tensor,
    compressed_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ckks_ops::add_contiguous_compressed_plaintext_component``.

    Torch schema::

        fhelium_ckks_ops::add_contiguous_compressed_plaintext_component(Tensor ciphertext_component, Tensor compressed_plaintext, Tensor rns_params) -> Tensor

    Args:
        ciphertext_component: torch.Tensor.
        compressed_plaintext: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ckks_ops.add_contiguous_compressed_plaintext_component(
        ciphertext_component, compressed_plaintext, rns_params
    )


def add_contiguous_compressed_plaintext_component_(
    ciphertext_component: torch.Tensor,
    compressed_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ckks_ops::add_contiguous_compressed_plaintext_component_``.

    Torch schema::

        fhelium_ckks_ops::add_contiguous_compressed_plaintext_component_(Tensor(a!) ciphertext_component, Tensor compressed_plaintext, Tensor rns_params) -> ()

    Args:
        ciphertext_component: torch.Tensor (modified in-place).
        compressed_plaintext: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ckks_ops.add_contiguous_compressed_plaintext_component_(
        ciphertext_component, compressed_plaintext, rns_params
    )


def add_cyclic_compressed_plaintext_component(
    ciphertext_component: torch.Tensor,
    compressed_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ckks_ops::add_cyclic_compressed_plaintext_component``.

    Torch schema::

        fhelium_ckks_ops::add_cyclic_compressed_plaintext_component(Tensor ciphertext_component, Tensor compressed_plaintext, Tensor rns_params) -> Tensor

    Args:
        ciphertext_component: torch.Tensor.
        compressed_plaintext: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ckks_ops.add_cyclic_compressed_plaintext_component(
        ciphertext_component, compressed_plaintext, rns_params
    )


def add_cyclic_compressed_plaintext_component_(
    ciphertext_component: torch.Tensor,
    compressed_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ckks_ops::add_cyclic_compressed_plaintext_component_``.

    Torch schema::

        fhelium_ckks_ops::add_cyclic_compressed_plaintext_component_(Tensor(a!) ciphertext_component, Tensor compressed_plaintext, Tensor rns_params) -> ()

    Args:
        ciphertext_component: torch.Tensor (modified in-place).
        compressed_plaintext: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ckks_ops.add_cyclic_compressed_plaintext_component_(
        ciphertext_component, compressed_plaintext, rns_params
    )


def add_prepared_plaintext_component(
    ciphertext_component: torch.Tensor,
    prepared_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ckks_ops::add_prepared_plaintext_component``.

    Torch schema::

        fhelium_ckks_ops::add_prepared_plaintext_component(Tensor ciphertext_component, Tensor prepared_plaintext, Tensor rns_params) -> Tensor

    Args:
        ciphertext_component: torch.Tensor.
        prepared_plaintext: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ckks_ops.add_prepared_plaintext_component(
        ciphertext_component, prepared_plaintext, rns_params
    )


def add_prepared_plaintext_component_(
    ciphertext_component: torch.Tensor,
    prepared_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ckks_ops::add_prepared_plaintext_component_``.

    Torch schema::

        fhelium_ckks_ops::add_prepared_plaintext_component_(Tensor(a!) ciphertext_component, Tensor prepared_plaintext, Tensor rns_params) -> ()

    Args:
        ciphertext_component: torch.Tensor (modified in-place).
        prepared_plaintext: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ckks_ops.add_prepared_plaintext_component_(
        ciphertext_component, prepared_plaintext, rns_params
    )


def add_strided_plaintext_component(
    ciphertext_component: torch.Tensor,
    strided_plaintext: torch.Tensor,
    implicit_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ckks_ops::add_strided_plaintext_component``.

    Torch schema::

        fhelium_ckks_ops::add_strided_plaintext_component(Tensor ciphertext_component, Tensor strided_plaintext, Tensor implicit_plaintext, Tensor rns_params) -> Tensor

    Args:
        ciphertext_component: torch.Tensor.
        strided_plaintext: torch.Tensor.
        implicit_plaintext: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ckks_ops.add_strided_plaintext_component(
        ciphertext_component, strided_plaintext, implicit_plaintext, rns_params
    )


def add_strided_plaintext_component_(
    ciphertext_component: torch.Tensor,
    strided_plaintext: torch.Tensor,
    implicit_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ckks_ops::add_strided_plaintext_component_``.

    Torch schema::

        fhelium_ckks_ops::add_strided_plaintext_component_(Tensor(a!) ciphertext_component, Tensor strided_plaintext, Tensor implicit_plaintext, Tensor rns_params) -> ()

    Args:
        ciphertext_component: torch.Tensor (modified in-place).
        strided_plaintext: torch.Tensor.
        implicit_plaintext: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ckks_ops.add_strided_plaintext_component_(
        ciphertext_component, strided_plaintext, implicit_plaintext, rns_params
    )


def apply_coefficient_galois_automorphism(
    residues: torch.Tensor,
    source_indices: torch.Tensor,
    source_sign: torch.Tensor,
    twice_modulus: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ckks_ops::apply_coefficient_galois_automorphism``.

    Torch schema::

        fhelium_ckks_ops::apply_coefficient_galois_automorphism(Tensor residues, Tensor source_indices, Tensor source_sign, Tensor twice_modulus) -> Tensor

    Args:
        residues: torch.Tensor.
        source_indices: torch.Tensor.
        source_sign: torch.Tensor.
        twice_modulus: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ckks_ops.apply_coefficient_galois_automorphism(
        residues, source_indices, source_sign, twice_modulus
    )


def apply_ntt_galois_automorphism(
    residues_ntt: torch.Tensor, source_indices: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ckks_ops::apply_ntt_galois_automorphism``.

    Torch schema::

        fhelium_ckks_ops::apply_ntt_galois_automorphism(Tensor residues_ntt, Tensor source_indices) -> Tensor

    Args:
        residues_ntt: torch.Tensor.
        source_indices: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ckks_ops.apply_ntt_galois_automorphism(
        residues_ntt, source_indices
    )


def keyswitch_accumulate_digit_products_(
    accumulator0_qp: torch.Tensor,
    accumulator1_qp: torch.Tensor,
    extended_digit_ntt_qp: torch.Tensor,
    key_switch_key_digit: torch.Tensor,
    rns_params: torch.Tensor,
    key_digit_row_start: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ckks_ops::keyswitch_accumulate_digit_products_``.

    Torch schema::

        fhelium_ckks_ops::keyswitch_accumulate_digit_products_(Tensor(a!) accumulator0_qp, Tensor(b!) accumulator1_qp, Tensor extended_digit_ntt_qp, Tensor key_switch_key_digit, Tensor rns_params, int key_digit_row_start) -> ()

    Args:
        accumulator0_qp: torch.Tensor (modified in-place).
        accumulator1_qp: torch.Tensor (modified in-place).
        extended_digit_ntt_qp: torch.Tensor.
        key_switch_key_digit: torch.Tensor.
        rns_params: torch.Tensor.
        key_digit_row_start: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ckks_ops.keyswitch_accumulate_digit_products_(
        accumulator0_qp,
        accumulator1_qp,
        extended_digit_ntt_qp,
        key_switch_key_digit,
        rns_params,
        key_digit_row_start,
    )


def keyswitch_moddown_qp_to_q(
    q_residues: torch.Tensor,
    p_residues: torch.Tensor,
    moddown_p_drop_inverses_montgomery: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ckks_ops::keyswitch_moddown_qp_to_q``.

    Torch schema::

        fhelium_ckks_ops::keyswitch_moddown_qp_to_q(Tensor q_residues, Tensor p_residues, Tensor moddown_p_drop_inverses_montgomery, Tensor rns_params) -> Tensor

    Args:
        q_residues: torch.Tensor.
        p_residues: torch.Tensor.
        moddown_p_drop_inverses_montgomery: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ckks_ops.keyswitch_moddown_qp_to_q(
        q_residues, p_residues, moddown_p_drop_inverses_montgomery, rns_params
    )


def rescale_drop_leading_prime_nearest(
    remaining_residues: torch.Tensor,
    drop_prime_inverse_mont: torch.Tensor,
    dropped_residue: torch.Tensor,
    rns_params: torch.Tensor,
    half_drop_prime: int,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ckks_ops::rescale_drop_leading_prime_nearest``.

    Torch schema::

        fhelium_ckks_ops::rescale_drop_leading_prime_nearest(Tensor remaining_residues, Tensor drop_prime_inverse_mont, Tensor dropped_residue, Tensor rns_params, int half_drop_prime) -> Tensor

    Args:
        remaining_residues: torch.Tensor.
        drop_prime_inverse_mont: torch.Tensor.
        dropped_residue: torch.Tensor.
        rns_params: torch.Tensor.
        half_drop_prime: int.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ckks_ops.rescale_drop_leading_prime_nearest(
        remaining_residues,
        drop_prime_inverse_mont,
        dropped_residue,
        rns_params,
        half_drop_prime,
    )


def rescale_drop_leading_prime_nearest_(
    remaining_residues: torch.Tensor,
    drop_prime_inverse_mont: torch.Tensor,
    dropped_residue: torch.Tensor,
    rns_params: torch.Tensor,
    half_drop_prime: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ckks_ops::rescale_drop_leading_prime_nearest_``.

    Torch schema::

        fhelium_ckks_ops::rescale_drop_leading_prime_nearest_(Tensor(a!) remaining_residues, Tensor drop_prime_inverse_mont, Tensor dropped_residue, Tensor rns_params, int half_drop_prime) -> ()

    Args:
        remaining_residues: torch.Tensor (modified in-place).
        drop_prime_inverse_mont: torch.Tensor.
        dropped_residue: torch.Tensor.
        rns_params: torch.Tensor.
        half_drop_prime: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ckks_ops.rescale_drop_leading_prime_nearest_(
        remaining_residues,
        drop_prime_inverse_mont,
        dropped_residue,
        rns_params,
        half_drop_prime,
    )


def rescale_drop_leading_prime_truncate(
    remaining_residues: torch.Tensor,
    drop_prime_inverse_mont: torch.Tensor,
    dropped_residue: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ckks_ops::rescale_drop_leading_prime_truncate``.

    Torch schema::

        fhelium_ckks_ops::rescale_drop_leading_prime_truncate(Tensor remaining_residues, Tensor drop_prime_inverse_mont, Tensor dropped_residue, Tensor rns_params) -> Tensor

    Args:
        remaining_residues: torch.Tensor.
        drop_prime_inverse_mont: torch.Tensor.
        dropped_residue: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ckks_ops.rescale_drop_leading_prime_truncate(
        remaining_residues, drop_prime_inverse_mont, dropped_residue, rns_params
    )


def rescale_drop_leading_prime_truncate_(
    remaining_residues: torch.Tensor,
    drop_prime_inverse_mont: torch.Tensor,
    dropped_residue: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ckks_ops::rescale_drop_leading_prime_truncate_``.

    Torch schema::

        fhelium_ckks_ops::rescale_drop_leading_prime_truncate_(Tensor(a!) remaining_residues, Tensor drop_prime_inverse_mont, Tensor dropped_residue, Tensor rns_params) -> ()

    Args:
        remaining_residues: torch.Tensor (modified in-place).
        drop_prime_inverse_mont: torch.Tensor.
        dropped_residue: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ckks_ops.rescale_drop_leading_prime_truncate_(
        remaining_residues, drop_prime_inverse_mont, dropped_residue, rns_params
    )
