# This file is generated by scripts/generate_native_wrappers.py.
# Do not edit!

from __future__ import annotations

import torch


@torch.library.register_fake(
    "fhelium_ckks_ops::add_contiguous_compressed_plaintext_component"
)
def _fake_fhelium_ckks_ops_add__contiguous__compressed__plaintext__component(
    ciphertext_component: torch.Tensor,
    compressed_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(ciphertext_component)


@torch.library.register_fake(
    "fhelium_ckks_ops::add_contiguous_compressed_plaintext_component_"
)
def _fake_fhelium_ckks_ops_add__contiguous__compressed__plaintext__component__(
    ciphertext_component: torch.Tensor,
    compressed_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ckks_ops::add_cyclic_compressed_plaintext_component"
)
def _fake_fhelium_ckks_ops_add__cyclic__compressed__plaintext__component(
    ciphertext_component: torch.Tensor,
    compressed_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(ciphertext_component)


@torch.library.register_fake(
    "fhelium_ckks_ops::add_cyclic_compressed_plaintext_component_"
)
def _fake_fhelium_ckks_ops_add__cyclic__compressed__plaintext__component__(
    ciphertext_component: torch.Tensor,
    compressed_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ckks_ops::add_prepared_plaintext_component"
)
def _fake_fhelium_ckks_ops_add__prepared__plaintext__component(
    ciphertext_component: torch.Tensor,
    prepared_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(ciphertext_component)


@torch.library.register_fake(
    "fhelium_ckks_ops::add_prepared_plaintext_component_"
)
def _fake_fhelium_ckks_ops_add__prepared__plaintext__component__(
    ciphertext_component: torch.Tensor,
    prepared_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ckks_ops::add_strided_plaintext_component"
)
def _fake_fhelium_ckks_ops_add__strided__plaintext__component(
    ciphertext_component: torch.Tensor,
    strided_plaintext: torch.Tensor,
    implicit_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(ciphertext_component)


@torch.library.register_fake(
    "fhelium_ckks_ops::add_strided_plaintext_component_"
)
def _fake_fhelium_ckks_ops_add__strided__plaintext__component__(
    ciphertext_component: torch.Tensor,
    strided_plaintext: torch.Tensor,
    implicit_plaintext: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ckks_ops::apply_coefficient_galois_automorphism"
)
def _fake_fhelium_ckks_ops_apply__coefficient__galois__automorphism(
    residues: torch.Tensor,
    source_indices: torch.Tensor,
    source_sign: torch.Tensor,
    twice_modulus: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(residues)


@torch.library.register_fake("fhelium_ckks_ops::apply_ntt_galois_automorphism")
def _fake_fhelium_ckks_ops_apply__ntt__galois__automorphism(
    residues_ntt: torch.Tensor, source_indices: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(residues_ntt)


@torch.library.register_fake(
    "fhelium_ckks_ops::keyswitch_accumulate_digit_products_"
)
def _fake_fhelium_ckks_ops_keyswitch__accumulate__digit__products__(
    accumulator0_qp: torch.Tensor,
    accumulator1_qp: torch.Tensor,
    extended_digit_ntt_qp: torch.Tensor,
    key_switch_key_digit: torch.Tensor,
    rns_params: torch.Tensor,
    key_digit_row_start: int,
) -> None:
    pass


@torch.library.register_fake("fhelium_ckks_ops::keyswitch_moddown_qp_to_q")
def _fake_fhelium_ckks_ops_keyswitch__moddown__qp__to__q(
    q_residues: torch.Tensor,
    p_residues: torch.Tensor,
    moddown_p_drop_inverses_montgomery: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(q_residues)


@torch.library.register_fake(
    "fhelium_ckks_ops::rescale_drop_leading_prime_nearest"
)
def _fake_fhelium_ckks_ops_rescale__drop__leading__prime__nearest(
    remaining_residues: torch.Tensor,
    drop_prime_inverse_mont: torch.Tensor,
    dropped_residue: torch.Tensor,
    rns_params: torch.Tensor,
    half_drop_prime: int,
) -> torch.Tensor:
    return torch.empty_like(remaining_residues)


@torch.library.register_fake(
    "fhelium_ckks_ops::rescale_drop_leading_prime_nearest_"
)
def _fake_fhelium_ckks_ops_rescale__drop__leading__prime__nearest__(
    remaining_residues: torch.Tensor,
    drop_prime_inverse_mont: torch.Tensor,
    dropped_residue: torch.Tensor,
    rns_params: torch.Tensor,
    half_drop_prime: int,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ckks_ops::rescale_drop_leading_prime_truncate"
)
def _fake_fhelium_ckks_ops_rescale__drop__leading__prime__truncate(
    remaining_residues: torch.Tensor,
    drop_prime_inverse_mont: torch.Tensor,
    dropped_residue: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(remaining_residues)


@torch.library.register_fake(
    "fhelium_ckks_ops::rescale_drop_leading_prime_truncate_"
)
def _fake_fhelium_ckks_ops_rescale__drop__leading__prime__truncate__(
    remaining_residues: torch.Tensor,
    drop_prime_inverse_mont: torch.Tensor,
    dropped_residue: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_diagnostic_ops::forward_ntt_montgomery_compact_grouped_smem_override_"
)
def _fake_fhelium_ntt_diagnostic_ops_forward__ntt__montgomery__compact__grouped__smem__override__(
    montgomery_residues: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
    shared_memory_log_n: int,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_diagnostic_ops::forward_ntt_montgomery_power_of_two_radix_compact_override_"
)
def _fake_fhelium_ntt_diagnostic_ops_forward__ntt__montgomery__power__of__two__radix__compact__override__(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
    shared_memory_log_n: int,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_diagnostic_ops::inverse_ntt_montgomery_power_of_two_radix_compact_override_"
)
def _fake_fhelium_ntt_diagnostic_ops_inverse__ntt__montgomery__power__of__two__radix__compact__override__(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
    shared_memory_log_n: int,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::forward_ntt_montgomery_compact_grouped_smem_"
)
def _fake_fhelium_ntt_ops_forward__ntt__montgomery__compact__grouped__smem__(
    montgomery_residues: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::forward_ntt_montgomery_compact_keyswitch_accumulate_"
)
def _fake_fhelium_ntt_ops_forward__ntt__montgomery__compact__keyswitch__accumulate__(
    coefficient_digit_qp: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    key_digit_qp: torch.Tensor,
    accumulator0_qp: torch.Tensor,
    accumulator1_qp: torch.Tensor,
    key_row_start: int,
) -> None:
    pass


@torch.library.register_fake("fhelium_ntt_ops::forward_ntt_montgomery_indexed_")
def _fake_fhelium_ntt_ops_forward__ntt__montgomery__indexed__(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::forward_ntt_montgomery_power_of_two_radix_compact_"
)
def _fake_fhelium_ntt_ops_forward__ntt__montgomery__power__of__two__radix__compact__(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::forward_ntt_to_montgomery_compact_grouped_smem"
)
def _fake_fhelium_ntt_ops_forward__ntt__to__montgomery__compact__grouped__smem(
    standard_residues: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> torch.Tensor:
    return torch.empty_like(standard_residues)


@torch.library.register_fake(
    "fhelium_ntt_ops::forward_ntt_to_montgomery_compact_grouped_smem_"
)
def _fake_fhelium_ntt_ops_forward__ntt__to__montgomery__compact__grouped__smem__(
    standard_residues: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::forward_ntt_to_montgomery_indexed"
)
def _fake_fhelium_ntt_ops_forward__ntt__to__montgomery__indexed(
    standard_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(standard_residues)


@torch.library.register_fake(
    "fhelium_ntt_ops::forward_ntt_to_montgomery_indexed_"
)
def _fake_fhelium_ntt_ops_forward__ntt__to__montgomery__indexed__(
    standard_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::forward_ntt_to_montgomery_power_of_two_radix_compact"
)
def _fake_fhelium_ntt_ops_forward__ntt__to__montgomery__power__of__two__radix__compact(
    standard_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(standard_residues)


@torch.library.register_fake(
    "fhelium_ntt_ops::forward_ntt_to_montgomery_power_of_two_radix_compact_"
)
def _fake_fhelium_ntt_ops_forward__ntt__to__montgomery__power__of__two__radix__compact__(
    standard_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_montgomery_compact_grouped_smem_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__montgomery__compact__grouped__smem__(
    montgomery_residues: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    pass


@torch.library.register_fake("fhelium_ntt_ops::inverse_ntt_montgomery_indexed_")
def _fake_fhelium_ntt_ops_inverse__ntt__montgomery__indexed__(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_montgomery_power_of_two_radix_compact_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__montgomery__power__of__two__radix__compact__(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_to_centered_compact_grouped_smem_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__to__centered__compact__grouped__smem__(
    montgomery_residues: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_to_centered_indexed_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__to__centered__indexed__(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_to_centered_power_of_two_radix_compact_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__to__centered__power__of__two__radix__compact__(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_to_standard_compact_grouped_smem_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__to__standard__compact__grouped__smem__(
    montgomery_residues: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_to_standard_indexed_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__to__standard__indexed__(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_to_standard_lazy_compact_grouped_smem_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__to__standard__lazy__compact__grouped__smem__(
    montgomery_residues: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_to_standard_lazy_indexed_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__to__standard__lazy__indexed__(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_to_standard_lazy_power_of_two_radix_compact_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__to__standard__lazy__power__of__two__radix__compact__(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_ntt_ops::inverse_ntt_to_standard_power_of_two_radix_compact_"
)
def _fake_fhelium_ntt_ops_inverse__ntt__to__standard__power__of__two__radix__compact__(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    pass


@torch.library.register_fake("fhelium_rns_ops::add_canonical")
def _fake_fhelium_rns_ops_add__canonical(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(lhs)


@torch.library.register_fake("fhelium_rns_ops::add_canonical_")
def _fake_fhelium_rns_ops_add__canonical__(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> None:
    pass


@torch.library.register_fake("fhelium_rns_ops::add_lazy")
def _fake_fhelium_rns_ops_add__lazy(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(lhs)


@torch.library.register_fake("fhelium_rns_ops::add_lazy_with_twice_modulus")
def _fake_fhelium_rns_ops_add__lazy__with__twice__modulus(
    lhs: torch.Tensor, rhs: torch.Tensor, twice_modulus: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(lhs)


@torch.library.register_fake("fhelium_rns_ops::canonicalize_residues_")
def _fake_fhelium_rns_ops_canonicalize__residues__(
    lazy_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    pass


@torch.library.register_fake("fhelium_rns_ops::center_residues_")
def _fake_fhelium_rns_ops_center__residues__(
    canonical_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    pass


@torch.library.register_fake("fhelium_rns_ops::from_montgomery_")
def _fake_fhelium_rns_ops_from__montgomery__(
    montgomery_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    pass


@torch.library.register_fake("fhelium_rns_ops::lift_centered_coefficients")
def _fake_fhelium_rns_ops_lift__centered__coefficients(
    centered_coefficients: torch.Tensor, twice_modulus: torch.Tensor
) -> torch.Tensor:
    return centered_coefficients.new_empty(
        (
            *centered_coefficients.shape[:-1],
            twice_modulus.size(0),
            centered_coefficients.size(-1),
        )
    )


@torch.library.register_fake(
    "fhelium_rns_ops::mixed_radix_basis_extend_to_montgomery"
)
def _fake_fhelium_rns_ops_mixed__radix__basis__extend__to__montgomery(
    mixed_radix_components: torch.Tensor,
    basis_extension_coefficients: torch.Tensor,
    rns_params: torch.Tensor,
    destination_row_count: int,
) -> torch.Tensor:
    return mixed_radix_components.new_empty(
        (
            *mixed_radix_components.shape[:-2],
            destination_row_count,
            mixed_radix_components.size(-1),
        )
    )


@torch.library.register_fake("fhelium_rns_ops::mixed_radix_decompose")
def _fake_fhelium_rns_ops_mixed__radix__decompose(
    source_residues: torch.Tensor,
    mixed_radix_normalizers: torch.Tensor,
    mixed_radix_propagation_coefficients: torch.Tensor,
    modulus_lo: torch.Tensor,
    modulus_hi: torch.Tensor,
    neg_inv_modulus_lo: torch.Tensor,
    neg_inv_modulus_hi: torch.Tensor,
) -> torch.Tensor:
    return torch.empty_like(source_residues)


@torch.library.register_fake("fhelium_rns_ops::montgomery_mul")
def _fake_fhelium_rns_ops_montgomery__mul(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(lhs)


@torch.library.register_fake(
    "fhelium_rns_ops::montgomery_mul_contiguous_compressed"
)
def _fake_fhelium_rns_ops_montgomery__mul__contiguous__compressed(
    lhs: torch.Tensor, compressed_rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(lhs)


@torch.library.register_fake(
    "fhelium_rns_ops::montgomery_mul_cyclic_compressed"
)
def _fake_fhelium_rns_ops_montgomery__mul__cyclic__compressed(
    lhs: torch.Tensor, compressed_rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(lhs)


@torch.library.register_fake("fhelium_rns_ops::montgomery_mul_row_scalars_")
def _fake_fhelium_rns_ops_montgomery__mul__row__scalars__(
    residues: torch.Tensor, row_scalars: torch.Tensor, rns_params: torch.Tensor
) -> None:
    pass


@torch.library.register_fake(
    "fhelium_rns_ops::montgomery_mul_row_scalars_canonical"
)
def _fake_fhelium_rns_ops_montgomery__mul__row__scalars__canonical(
    residues: torch.Tensor, row_scalars: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(residues)


@torch.library.register_fake("fhelium_rns_ops::shift_residues_positive_")
def _fake_fhelium_rns_ops_shift__residues__positive__(
    centered_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    pass


@torch.library.register_fake("fhelium_rns_ops::sub_canonical")
def _fake_fhelium_rns_ops_sub__canonical(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(lhs)


@torch.library.register_fake("fhelium_rns_ops::sub_canonical_")
def _fake_fhelium_rns_ops_sub__canonical__(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> None:
    pass


@torch.library.register_fake("fhelium_rns_ops::sub_lazy")
def _fake_fhelium_rns_ops_sub__lazy(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    return torch.empty_like(lhs)


@torch.library.register_fake("fhelium_rns_ops::to_montgomery_")
def _fake_fhelium_rns_ops_to__montgomery__(
    standard_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    pass
