# This file is generated by scripts/generate_native_wrappers.py.
# Do not edit!

from __future__ import annotations

import torch


def _require_native() -> None:
    from fhelium.native import require_native

    require_native()


def forward_ntt_montgomery_compact_grouped_smem_override_(
    montgomery_residues: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
    shared_memory_log_n: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_diagnostic_ops::forward_ntt_montgomery_compact_grouped_smem_override_``.

    Torch schema::

        fhelium_ntt_diagnostic_ops::forward_ntt_montgomery_compact_grouped_smem_override_(Tensor(a!) montgomery_residues, Tensor forward_twiddles, Tensor rns_params, int grouped_stage_count, int shared_memory_log_n) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        forward_twiddles: torch.Tensor.
        rns_params: torch.Tensor.
        grouped_stage_count: int.
        shared_memory_log_n: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_diagnostic_ops.forward_ntt_montgomery_compact_grouped_smem_override_(
        montgomery_residues,
        forward_twiddles,
        rns_params,
        grouped_stage_count,
        shared_memory_log_n,
    )


def forward_ntt_montgomery_power_of_two_radix_compact_override_(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
    shared_memory_log_n: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_diagnostic_ops::forward_ntt_montgomery_power_of_two_radix_compact_override_``.

    Torch schema::

        fhelium_ntt_diagnostic_ops::forward_ntt_montgomery_power_of_two_radix_compact_override_(Tensor(a!) montgomery_residues, Tensor outer_twiddles, Tensor radix_root_powers, Tensor rns_params, int shared_memory_log_n) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        outer_twiddles: torch.Tensor.
        radix_root_powers: torch.Tensor.
        rns_params: torch.Tensor.
        shared_memory_log_n: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_diagnostic_ops.forward_ntt_montgomery_power_of_two_radix_compact_override_(
        montgomery_residues,
        outer_twiddles,
        radix_root_powers,
        rns_params,
        shared_memory_log_n,
    )


def inverse_ntt_montgomery_power_of_two_radix_compact_override_(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
    shared_memory_log_n: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_diagnostic_ops::inverse_ntt_montgomery_power_of_two_radix_compact_override_``.

    Torch schema::

        fhelium_ntt_diagnostic_ops::inverse_ntt_montgomery_power_of_two_radix_compact_override_(Tensor(a!) montgomery_residues, Tensor outer_twiddles, Tensor radix_root_powers, Tensor rns_params, int shared_memory_log_n) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        outer_twiddles: torch.Tensor.
        radix_root_powers: torch.Tensor.
        rns_params: torch.Tensor.
        shared_memory_log_n: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_diagnostic_ops.inverse_ntt_montgomery_power_of_two_radix_compact_override_(
        montgomery_residues,
        outer_twiddles,
        radix_root_powers,
        rns_params,
        shared_memory_log_n,
    )
