# This file is generated by scripts/generate_native_wrappers.py.
# Do not edit!

from __future__ import annotations

import torch


def _require_native() -> None:
    from fhelium.native import require_native

    require_native()


def forward_ntt_montgomery_compact_grouped_smem_(
    montgomery_residues: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_montgomery_compact_grouped_smem_``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_montgomery_compact_grouped_smem_(Tensor(a!) montgomery_residues, Tensor forward_twiddles, Tensor rns_params, int grouped_stage_count) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        forward_twiddles: torch.Tensor.
        rns_params: torch.Tensor.
        grouped_stage_count: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.forward_ntt_montgomery_compact_grouped_smem_(
        montgomery_residues, forward_twiddles, rns_params, grouped_stage_count
    )


def forward_ntt_montgomery_compact_keyswitch_accumulate_(
    coefficient_digit_qp: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    key_digit_qp: torch.Tensor,
    accumulator0_qp: torch.Tensor,
    accumulator1_qp: torch.Tensor,
    key_row_start: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_montgomery_compact_keyswitch_accumulate_``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_montgomery_compact_keyswitch_accumulate_(Tensor(a!) coefficient_digit_qp, Tensor forward_twiddles, Tensor rns_params, Tensor key_digit_qp, Tensor(b!) accumulator0_qp, Tensor(c!) accumulator1_qp, int key_row_start) -> ()

    Args:
        coefficient_digit_qp: torch.Tensor (modified in-place).
        forward_twiddles: torch.Tensor.
        rns_params: torch.Tensor.
        key_digit_qp: torch.Tensor.
        accumulator0_qp: torch.Tensor (modified in-place).
        accumulator1_qp: torch.Tensor (modified in-place).
        key_row_start: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.forward_ntt_montgomery_compact_keyswitch_accumulate_(
        coefficient_digit_qp,
        forward_twiddles,
        rns_params,
        key_digit_qp,
        accumulator0_qp,
        accumulator1_qp,
        key_row_start,
    )


def forward_ntt_montgomery_indexed_(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_montgomery_indexed_``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_montgomery_indexed_(Tensor(a!) montgomery_residues, Tensor even_indices, Tensor odd_indices, Tensor forward_twiddles, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        even_indices: torch.Tensor.
        odd_indices: torch.Tensor.
        forward_twiddles: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.forward_ntt_montgomery_indexed_(
        montgomery_residues,
        even_indices,
        odd_indices,
        forward_twiddles,
        rns_params,
    )


def forward_ntt_montgomery_power_of_two_radix_compact_(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_montgomery_power_of_two_radix_compact_``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_montgomery_power_of_two_radix_compact_(Tensor(a!) montgomery_residues, Tensor outer_twiddles, Tensor radix_root_powers, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        outer_twiddles: torch.Tensor.
        radix_root_powers: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.forward_ntt_montgomery_power_of_two_radix_compact_(
        montgomery_residues, outer_twiddles, radix_root_powers, rns_params
    )


def forward_ntt_to_montgomery_compact_grouped_smem(
    standard_residues: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_to_montgomery_compact_grouped_smem``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_to_montgomery_compact_grouped_smem(Tensor standard_residues, Tensor forward_twiddles, Tensor rns_params, int grouped_stage_count) -> Tensor

    Args:
        standard_residues: torch.Tensor.
        forward_twiddles: torch.Tensor.
        rns_params: torch.Tensor.
        grouped_stage_count: int.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ntt_ops.forward_ntt_to_montgomery_compact_grouped_smem(
        standard_residues, forward_twiddles, rns_params, grouped_stage_count
    )


def forward_ntt_to_montgomery_compact_grouped_smem_(
    standard_residues: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_to_montgomery_compact_grouped_smem_``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_to_montgomery_compact_grouped_smem_(Tensor(a!) standard_residues, Tensor forward_twiddles, Tensor rns_params, int grouped_stage_count) -> ()

    Args:
        standard_residues: torch.Tensor (modified in-place).
        forward_twiddles: torch.Tensor.
        rns_params: torch.Tensor.
        grouped_stage_count: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.forward_ntt_to_montgomery_compact_grouped_smem_(
        standard_residues, forward_twiddles, rns_params, grouped_stage_count
    )


def forward_ntt_to_montgomery_indexed(
    standard_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_to_montgomery_indexed``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_to_montgomery_indexed(Tensor standard_residues, Tensor even_indices, Tensor odd_indices, Tensor forward_twiddles, Tensor rns_params) -> Tensor

    Args:
        standard_residues: torch.Tensor.
        even_indices: torch.Tensor.
        odd_indices: torch.Tensor.
        forward_twiddles: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ntt_ops.forward_ntt_to_montgomery_indexed(
        standard_residues,
        even_indices,
        odd_indices,
        forward_twiddles,
        rns_params,
    )


def forward_ntt_to_montgomery_indexed_(
    standard_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    forward_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_to_montgomery_indexed_``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_to_montgomery_indexed_(Tensor(a!) standard_residues, Tensor even_indices, Tensor odd_indices, Tensor forward_twiddles, Tensor rns_params) -> ()

    Args:
        standard_residues: torch.Tensor (modified in-place).
        even_indices: torch.Tensor.
        odd_indices: torch.Tensor.
        forward_twiddles: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.forward_ntt_to_montgomery_indexed_(
        standard_residues,
        even_indices,
        odd_indices,
        forward_twiddles,
        rns_params,
    )


def forward_ntt_to_montgomery_power_of_two_radix_compact(
    standard_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_to_montgomery_power_of_two_radix_compact``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_to_montgomery_power_of_two_radix_compact(Tensor standard_residues, Tensor outer_twiddles, Tensor radix_root_powers, Tensor rns_params) -> Tensor

    Args:
        standard_residues: torch.Tensor.
        outer_twiddles: torch.Tensor.
        radix_root_powers: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_ntt_ops.forward_ntt_to_montgomery_power_of_two_radix_compact(
        standard_residues, outer_twiddles, radix_root_powers, rns_params
    )


def forward_ntt_to_montgomery_power_of_two_radix_compact_(
    standard_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::forward_ntt_to_montgomery_power_of_two_radix_compact_``.

    Torch schema::

        fhelium_ntt_ops::forward_ntt_to_montgomery_power_of_two_radix_compact_(Tensor(a!) standard_residues, Tensor outer_twiddles, Tensor radix_root_powers, Tensor rns_params) -> ()

    Args:
        standard_residues: torch.Tensor (modified in-place).
        outer_twiddles: torch.Tensor.
        radix_root_powers: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.forward_ntt_to_montgomery_power_of_two_radix_compact_(
        standard_residues, outer_twiddles, radix_root_powers, rns_params
    )


def inverse_ntt_montgomery_compact_grouped_smem_(
    montgomery_residues: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_montgomery_compact_grouped_smem_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_montgomery_compact_grouped_smem_(Tensor(a!) montgomery_residues, Tensor inverse_twiddles, Tensor rns_params, int grouped_stage_count) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        inverse_twiddles: torch.Tensor.
        rns_params: torch.Tensor.
        grouped_stage_count: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_montgomery_compact_grouped_smem_(
        montgomery_residues, inverse_twiddles, rns_params, grouped_stage_count
    )


def inverse_ntt_montgomery_indexed_(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_montgomery_indexed_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_montgomery_indexed_(Tensor(a!) montgomery_residues, Tensor even_indices, Tensor odd_indices, Tensor inverse_twiddles, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        even_indices: torch.Tensor.
        odd_indices: torch.Tensor.
        inverse_twiddles: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_montgomery_indexed_(
        montgomery_residues,
        even_indices,
        odd_indices,
        inverse_twiddles,
        rns_params,
    )


def inverse_ntt_montgomery_power_of_two_radix_compact_(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_montgomery_power_of_two_radix_compact_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_montgomery_power_of_two_radix_compact_(Tensor(a!) montgomery_residues, Tensor outer_twiddles, Tensor radix_root_powers, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        outer_twiddles: torch.Tensor.
        radix_root_powers: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_montgomery_power_of_two_radix_compact_(
        montgomery_residues, outer_twiddles, radix_root_powers, rns_params
    )


def inverse_ntt_to_centered_compact_grouped_smem_(
    montgomery_residues: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_to_centered_compact_grouped_smem_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_to_centered_compact_grouped_smem_(Tensor(a!) montgomery_residues, Tensor inverse_twiddles, Tensor rns_params, int grouped_stage_count) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        inverse_twiddles: torch.Tensor.
        rns_params: torch.Tensor.
        grouped_stage_count: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_to_centered_compact_grouped_smem_(
        montgomery_residues, inverse_twiddles, rns_params, grouped_stage_count
    )


def inverse_ntt_to_centered_indexed_(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_to_centered_indexed_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_to_centered_indexed_(Tensor(a!) montgomery_residues, Tensor even_indices, Tensor odd_indices, Tensor inverse_twiddles, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        even_indices: torch.Tensor.
        odd_indices: torch.Tensor.
        inverse_twiddles: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_to_centered_indexed_(
        montgomery_residues,
        even_indices,
        odd_indices,
        inverse_twiddles,
        rns_params,
    )


def inverse_ntt_to_centered_power_of_two_radix_compact_(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_to_centered_power_of_two_radix_compact_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_to_centered_power_of_two_radix_compact_(Tensor(a!) montgomery_residues, Tensor outer_twiddles, Tensor radix_root_powers, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        outer_twiddles: torch.Tensor.
        radix_root_powers: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_to_centered_power_of_two_radix_compact_(
        montgomery_residues, outer_twiddles, radix_root_powers, rns_params
    )


def inverse_ntt_to_standard_compact_grouped_smem_(
    montgomery_residues: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_to_standard_compact_grouped_smem_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_to_standard_compact_grouped_smem_(Tensor(a!) montgomery_residues, Tensor inverse_twiddles, Tensor rns_params, int grouped_stage_count) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        inverse_twiddles: torch.Tensor.
        rns_params: torch.Tensor.
        grouped_stage_count: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_to_standard_compact_grouped_smem_(
        montgomery_residues, inverse_twiddles, rns_params, grouped_stage_count
    )


def inverse_ntt_to_standard_indexed_(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_to_standard_indexed_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_to_standard_indexed_(Tensor(a!) montgomery_residues, Tensor even_indices, Tensor odd_indices, Tensor inverse_twiddles, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        even_indices: torch.Tensor.
        odd_indices: torch.Tensor.
        inverse_twiddles: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_to_standard_indexed_(
        montgomery_residues,
        even_indices,
        odd_indices,
        inverse_twiddles,
        rns_params,
    )


def inverse_ntt_to_standard_lazy_compact_grouped_smem_(
    montgomery_residues: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
    grouped_stage_count: int,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_to_standard_lazy_compact_grouped_smem_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_to_standard_lazy_compact_grouped_smem_(Tensor(a!) montgomery_residues, Tensor inverse_twiddles, Tensor rns_params, int grouped_stage_count) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        inverse_twiddles: torch.Tensor.
        rns_params: torch.Tensor.
        grouped_stage_count: int.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_to_standard_lazy_compact_grouped_smem_(
        montgomery_residues, inverse_twiddles, rns_params, grouped_stage_count
    )


def inverse_ntt_to_standard_lazy_indexed_(
    montgomery_residues: torch.Tensor,
    even_indices: torch.Tensor,
    odd_indices: torch.Tensor,
    inverse_twiddles: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_to_standard_lazy_indexed_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_to_standard_lazy_indexed_(Tensor(a!) montgomery_residues, Tensor even_indices, Tensor odd_indices, Tensor inverse_twiddles, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        even_indices: torch.Tensor.
        odd_indices: torch.Tensor.
        inverse_twiddles: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_to_standard_lazy_indexed_(
        montgomery_residues,
        even_indices,
        odd_indices,
        inverse_twiddles,
        rns_params,
    )


def inverse_ntt_to_standard_lazy_power_of_two_radix_compact_(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_to_standard_lazy_power_of_two_radix_compact_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_to_standard_lazy_power_of_two_radix_compact_(Tensor(a!) montgomery_residues, Tensor outer_twiddles, Tensor radix_root_powers, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        outer_twiddles: torch.Tensor.
        radix_root_powers: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_to_standard_lazy_power_of_two_radix_compact_(
        montgomery_residues, outer_twiddles, radix_root_powers, rns_params
    )


def inverse_ntt_to_standard_power_of_two_radix_compact_(
    montgomery_residues: torch.Tensor,
    outer_twiddles: torch.Tensor,
    radix_root_powers: torch.Tensor,
    rns_params: torch.Tensor,
) -> None:
    """
    Typed wrapper for ``fhelium_ntt_ops::inverse_ntt_to_standard_power_of_two_radix_compact_``.

    Torch schema::

        fhelium_ntt_ops::inverse_ntt_to_standard_power_of_two_radix_compact_(Tensor(a!) montgomery_residues, Tensor outer_twiddles, Tensor radix_root_powers, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        outer_twiddles: torch.Tensor.
        radix_root_powers: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_ntt_ops.inverse_ntt_to_standard_power_of_two_radix_compact_(
        montgomery_residues, outer_twiddles, radix_root_powers, rns_params
    )
