# This file is generated by scripts/generate_native_wrappers.py.
# Do not edit!

from __future__ import annotations

import torch


def _require_native() -> None:
    from fhelium.native import require_native

    require_native()


def add_canonical(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::add_canonical``.

    Torch schema::

        fhelium_rns_ops::add_canonical(Tensor lhs, Tensor rhs, Tensor rns_params) -> Tensor

    Args:
        lhs: torch.Tensor.
        rhs: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.add_canonical(lhs, rhs, rns_params)


def add_canonical_(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> None:
    """
    Typed wrapper for ``fhelium_rns_ops::add_canonical_``.

    Torch schema::

        fhelium_rns_ops::add_canonical_(Tensor(a!) lhs, Tensor rhs, Tensor rns_params) -> ()

    Args:
        lhs: torch.Tensor (modified in-place).
        rhs: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_rns_ops.add_canonical_(lhs, rhs, rns_params)


def add_lazy(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::add_lazy``.

    Torch schema::

        fhelium_rns_ops::add_lazy(Tensor lhs, Tensor rhs, Tensor rns_params) -> Tensor

    Args:
        lhs: torch.Tensor.
        rhs: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.add_lazy(lhs, rhs, rns_params)


def add_lazy_with_twice_modulus(
    lhs: torch.Tensor, rhs: torch.Tensor, twice_modulus: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::add_lazy_with_twice_modulus``.

    Torch schema::

        fhelium_rns_ops::add_lazy_with_twice_modulus(Tensor lhs, Tensor rhs, Tensor twice_modulus) -> Tensor

    Args:
        lhs: torch.Tensor.
        rhs: torch.Tensor.
        twice_modulus: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.add_lazy_with_twice_modulus(
        lhs, rhs, twice_modulus
    )


def canonicalize_residues_(
    lazy_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    """
    Typed wrapper for ``fhelium_rns_ops::canonicalize_residues_``.

    Torch schema::

        fhelium_rns_ops::canonicalize_residues_(Tensor(a!) lazy_residues, Tensor rns_params) -> ()

    Args:
        lazy_residues: torch.Tensor (modified in-place).
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_rns_ops.canonicalize_residues_(lazy_residues, rns_params)


def center_residues_(
    canonical_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    """
    Typed wrapper for ``fhelium_rns_ops::center_residues_``.

    Torch schema::

        fhelium_rns_ops::center_residues_(Tensor(a!) canonical_residues, Tensor rns_params) -> ()

    Args:
        canonical_residues: torch.Tensor (modified in-place).
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_rns_ops.center_residues_(canonical_residues, rns_params)


def from_montgomery_(
    montgomery_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    """
    Typed wrapper for ``fhelium_rns_ops::from_montgomery_``.

    Torch schema::

        fhelium_rns_ops::from_montgomery_(Tensor(a!) montgomery_residues, Tensor rns_params) -> ()

    Args:
        montgomery_residues: torch.Tensor (modified in-place).
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_rns_ops.from_montgomery_(montgomery_residues, rns_params)


def lift_centered_coefficients(
    centered_coefficients: torch.Tensor, twice_modulus: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::lift_centered_coefficients``.

    Torch schema::

        fhelium_rns_ops::lift_centered_coefficients(Tensor centered_coefficients, Tensor twice_modulus) -> Tensor

    Args:
        centered_coefficients: torch.Tensor.
        twice_modulus: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.lift_centered_coefficients(
        centered_coefficients, twice_modulus
    )


def mixed_radix_basis_extend_to_montgomery(
    mixed_radix_components: torch.Tensor,
    basis_extension_coefficients: torch.Tensor,
    rns_params: torch.Tensor,
    destination_row_count: int,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::mixed_radix_basis_extend_to_montgomery``.

    Torch schema::

        fhelium_rns_ops::mixed_radix_basis_extend_to_montgomery(Tensor mixed_radix_components, Tensor basis_extension_coefficients, Tensor rns_params, int destination_row_count) -> Tensor

    Args:
        mixed_radix_components: torch.Tensor.
        basis_extension_coefficients: torch.Tensor.
        rns_params: torch.Tensor.
        destination_row_count: int.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.mixed_radix_basis_extend_to_montgomery(
        mixed_radix_components,
        basis_extension_coefficients,
        rns_params,
        destination_row_count,
    )


def mixed_radix_decompose(
    source_residues: torch.Tensor,
    mixed_radix_normalizers: torch.Tensor,
    mixed_radix_propagation_coefficients: torch.Tensor,
    modulus_lo: torch.Tensor,
    modulus_hi: torch.Tensor,
    neg_inv_modulus_lo: torch.Tensor,
    neg_inv_modulus_hi: torch.Tensor,
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::mixed_radix_decompose``.

    Torch schema::

        fhelium_rns_ops::mixed_radix_decompose(Tensor source_residues, Tensor mixed_radix_normalizers, Tensor mixed_radix_propagation_coefficients, Tensor modulus_lo, Tensor modulus_hi, Tensor neg_inv_modulus_lo, Tensor neg_inv_modulus_hi) -> Tensor

    Args:
        source_residues: torch.Tensor.
        mixed_radix_normalizers: torch.Tensor.
        mixed_radix_propagation_coefficients: torch.Tensor.
        modulus_lo: torch.Tensor.
        modulus_hi: torch.Tensor.
        neg_inv_modulus_lo: torch.Tensor.
        neg_inv_modulus_hi: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.mixed_radix_decompose(
        source_residues,
        mixed_radix_normalizers,
        mixed_radix_propagation_coefficients,
        modulus_lo,
        modulus_hi,
        neg_inv_modulus_lo,
        neg_inv_modulus_hi,
    )


def montgomery_mul(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::montgomery_mul``.

    Torch schema::

        fhelium_rns_ops::montgomery_mul(Tensor lhs, Tensor rhs, Tensor rns_params) -> Tensor

    Args:
        lhs: torch.Tensor.
        rhs: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.montgomery_mul(lhs, rhs, rns_params)


def montgomery_mul_contiguous_compressed(
    lhs: torch.Tensor, compressed_rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::montgomery_mul_contiguous_compressed``.

    Torch schema::

        fhelium_rns_ops::montgomery_mul_contiguous_compressed(Tensor lhs, Tensor compressed_rhs, Tensor rns_params) -> Tensor

    Args:
        lhs: torch.Tensor.
        compressed_rhs: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.montgomery_mul_contiguous_compressed(
        lhs, compressed_rhs, rns_params
    )


def montgomery_mul_cyclic_compressed(
    lhs: torch.Tensor, compressed_rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::montgomery_mul_cyclic_compressed``.

    Torch schema::

        fhelium_rns_ops::montgomery_mul_cyclic_compressed(Tensor lhs, Tensor compressed_rhs, Tensor rns_params) -> Tensor

    Args:
        lhs: torch.Tensor.
        compressed_rhs: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.montgomery_mul_cyclic_compressed(
        lhs, compressed_rhs, rns_params
    )


def montgomery_mul_row_scalars_(
    residues: torch.Tensor, row_scalars: torch.Tensor, rns_params: torch.Tensor
) -> None:
    """
    Typed wrapper for ``fhelium_rns_ops::montgomery_mul_row_scalars_``.

    Torch schema::

        fhelium_rns_ops::montgomery_mul_row_scalars_(Tensor(a!) residues, Tensor row_scalars, Tensor rns_params) -> ()

    Args:
        residues: torch.Tensor (modified in-place).
        row_scalars: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_rns_ops.montgomery_mul_row_scalars_(
        residues, row_scalars, rns_params
    )


def montgomery_mul_row_scalars_canonical(
    residues: torch.Tensor, row_scalars: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::montgomery_mul_row_scalars_canonical``.

    Torch schema::

        fhelium_rns_ops::montgomery_mul_row_scalars_canonical(Tensor residues, Tensor row_scalars, Tensor rns_params) -> Tensor

    Args:
        residues: torch.Tensor.
        row_scalars: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.montgomery_mul_row_scalars_canonical(
        residues, row_scalars, rns_params
    )


def shift_residues_positive_(
    centered_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    """
    Typed wrapper for ``fhelium_rns_ops::shift_residues_positive_``.

    Torch schema::

        fhelium_rns_ops::shift_residues_positive_(Tensor(a!) centered_residues, Tensor rns_params) -> ()

    Args:
        centered_residues: torch.Tensor (modified in-place).
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_rns_ops.shift_residues_positive_(
        centered_residues, rns_params
    )


def sub_canonical(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::sub_canonical``.

    Torch schema::

        fhelium_rns_ops::sub_canonical(Tensor lhs, Tensor rhs, Tensor rns_params) -> Tensor

    Args:
        lhs: torch.Tensor.
        rhs: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.sub_canonical(lhs, rhs, rns_params)


def sub_canonical_(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> None:
    """
    Typed wrapper for ``fhelium_rns_ops::sub_canonical_``.

    Torch schema::

        fhelium_rns_ops::sub_canonical_(Tensor(a!) lhs, Tensor rhs, Tensor rns_params) -> ()

    Args:
        lhs: torch.Tensor (modified in-place).
        rhs: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_rns_ops.sub_canonical_(lhs, rhs, rns_params)


def sub_lazy(
    lhs: torch.Tensor, rhs: torch.Tensor, rns_params: torch.Tensor
) -> torch.Tensor:
    """
    Typed wrapper for ``fhelium_rns_ops::sub_lazy``.

    Torch schema::

        fhelium_rns_ops::sub_lazy(Tensor lhs, Tensor rhs, Tensor rns_params) -> Tensor

    Args:
        lhs: torch.Tensor.
        rhs: torch.Tensor.
        rns_params: torch.Tensor.

    Returns: torch.Tensor.
    """
    _require_native()
    return torch.ops.fhelium_rns_ops.sub_lazy(lhs, rhs, rns_params)


def to_montgomery_(
    standard_residues: torch.Tensor, rns_params: torch.Tensor
) -> None:
    """
    Typed wrapper for ``fhelium_rns_ops::to_montgomery_``.

    Torch schema::

        fhelium_rns_ops::to_montgomery_(Tensor(a!) standard_residues, Tensor rns_params) -> ()

    Args:
        standard_residues: torch.Tensor (modified in-place).
        rns_params: torch.Tensor.

    Returns: None.
    """
    _require_native()
    torch.ops.fhelium_rns_ops.to_montgomery_(standard_residues, rns_params)
