#!/usr/bin/env python3
"""Generate typed Python facades for FHElium custom Torch operators.

The generated files are intentionally committed: they make dynamically registered
``torch.ops`` operators visible to IDEs, type checkers, and autocomplete.

Invoke this file directly from the repository root. It intentionally lives
outside ``fhelium.native.wrapper`` so wrapper generation never imports the
runtime package that it is responsible for generating.

Design goals:
- discover real schemas from the PyTorch dispatcher after loading local .so files;
- preserve PyTorch alias/mutation semantics in docstrings;
- enforce trailing-underscore names for mutating operators;
- keep generated wrappers thin and predictable.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import keyword
import shutil
import subprocess
import sysconfig
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from textwrap import indent

import torch

TYPE_MAP = {
    "Tensor": "torch.Tensor",
    "List[Tensor]": "list[torch.Tensor]",
    "List[List[Tensor]]": "list[list[torch.Tensor]]",
    "int": "int",
    "List[int]": "list[int]",
    "float": "float",
    "bool": "bool",
    "str": "str",
    "ScalarType": "torch.dtype",
}

GENERATED_MARKER = (
    "# This file is generated by scripts/generate_native_wrappers.py."
)

HEADER_TEMPLATE = """{generated_marker}
# Do not edit!

from __future__ import annotations

{typing_import}
import torch

{native_guard}
"""


@dataclass(frozen=True)
class ArgSpec:
    name: str
    py_name: str
    type_repr: str
    py_type: str
    is_write: bool
    is_out: bool
    kwarg_only: bool
    default: object | None = None
    has_default: bool = False


@dataclass(frozen=True)
class ReturnSpec:
    type_repr: str
    py_type: str


@dataclass(frozen=True)
class OpSpec:
    namespace: str
    name: str
    overload_name: str
    schema: str
    args: tuple[ArgSpec, ...]
    returns: tuple[ReturnSpec, ...]

    @property
    def python_name(self) -> str:
        if not self.overload_name:
            return self.name
        return f"{self.name}_{self.overload_name}"

    @property
    def return_annotation(self) -> str:
        if not self.returns:
            return "None"
        if len(self.returns) == 1:
            return self.returns[0].py_type
        return "tuple[" + ", ".join(ret.py_type for ret in self.returns) + "]"

    @property
    def mutating_args(self) -> tuple[ArgSpec, ...]:
        return tuple(arg for arg in self.args if arg.is_write)


@dataclass(frozen=True)
class FakeTensorShapeRule:
    """Metadata for a tensor-returning op whose output is not input-shaped."""

    like_arg: str
    shape_expression: str


FAKE_TENSOR_SHAPE_RULES = {
    "fhelium_rns_ops::mixed_radix_basis_extend_to_montgomery": FakeTensorShapeRule(
        like_arg="mixed_radix_components",
        shape_expression="(*mixed_radix_components.shape[:-2], destination_row_count, mixed_radix_components.size(-1))",
    ),
    "fhelium_rns_ops::lift_centered_coefficients": FakeTensorShapeRule(
        like_arg="centered_coefficients",
        shape_expression="(*centered_coefficients.shape[:-1], twice_modulus.size(0), centered_coefficients.size(-1))",
    ),
}


def type_to_annotation(type_repr: str) -> str:
    return TYPE_MAP.get(type_repr, "Any")


def sanitize_arg_name(name: str, used: set[str]) -> str:
    py_name = name or "arg"
    if keyword.iskeyword(py_name):
        py_name += "_"
    if not py_name.isidentifier():
        py_name = "arg"
    base = py_name
    suffix = 1
    while py_name in used:
        py_name = f"{base}_{suffix}"
        suffix += 1
    used.add(py_name)
    return py_name


def load_libraries(lib_dir: Path, *, verbose: bool) -> list[Path]:
    if not lib_dir.is_dir():
        raise FileNotFoundError(f"Torch-op directory not found: {lib_dir}")

    extension_suffix = sysconfig.get_config_var("EXT_SUFFIX")
    if not extension_suffix:
        raise RuntimeError("Python did not report EXT_SUFFIX")
    path = lib_dir / f"_ops{extension_suffix}"
    if not path.is_file():
        raise RuntimeError(f"No current-ABI FHElium _ops library found: {path}")
    if verbose:
        print(f"  -> loading {path}")
    torch.ops.load_library(str(path))
    return [path]


def dispatcher_op_names(namespace_prefix: str) -> list[str]:
    names = torch._C._dispatch_get_all_op_names()
    return sorted(name for name in names if name.startswith(namespace_prefix))


def schema_to_spec(schema: torch.FunctionSchema) -> OpSpec:
    used_names: set[str] = set()
    args = []
    for arg in schema.arguments:
        type_repr = str(arg.type)
        has_default = arg.has_default_value()
        args.append(
            ArgSpec(
                name=arg.name,
                py_name=sanitize_arg_name(arg.name, used_names),
                type_repr=type_repr,
                py_type=type_to_annotation(type_repr),
                is_write=bool(arg.is_write),
                is_out=bool(arg.is_out),
                kwarg_only=bool(arg.kwarg_only),
                default=arg.default_value if has_default else None,
                has_default=has_default,
            )
        )

    returns = tuple(
        ReturnSpec(
            type_repr=str(ret.type), py_type=type_to_annotation(str(ret.type))
        )
        for ret in schema.returns
    )
    namespace, name = schema.name.split("::", 1)
    return OpSpec(
        namespace=namespace,
        name=name,
        overload_name=schema.overload_name,
        schema=str(schema),
        args=tuple(args),
        returns=returns,
    )


def collect_specs(namespace_prefix: str) -> dict[str, list[OpSpec]]:
    specs: dict[str, list[OpSpec]] = {}
    for op_name in dispatcher_op_names(namespace_prefix):
        for schema in torch._C._jit_get_schemas_for_operator(op_name):
            spec = schema_to_spec(schema)
            specs.setdefault(spec.namespace, []).append(spec)

    for namespace in specs:
        specs[namespace].sort(key=lambda spec: (spec.name, spec.overload_name))
    return dict(sorted(specs.items()))


def validate_specs(specs: dict[str, list[OpSpec]]) -> None:
    for namespace, ops in specs.items():
        seen_python_names: set[str] = set()
        for spec in ops:
            if spec.python_name in seen_python_names:
                raise ValueError(
                    f"Duplicate generated wrapper name {namespace}.{spec.python_name}"
                )
            seen_python_names.add(spec.python_name)

            if spec.mutating_args and not spec.name.endswith("_"):
                args = ", ".join(arg.name for arg in spec.mutating_args)
                raise ValueError(
                    f"Mutating op {namespace}::{spec.name} writes [{args}] "
                    "but does not follow PyTorch trailing-underscore naming"
                )


def format_default(arg: ArgSpec) -> str:
    if not arg.has_default:
        return ""
    return f" = {arg.default!r}"


def format_signature_args(args: Iterable[ArgSpec]) -> str:
    rendered: list[str] = []
    inserted_kw_marker = False
    for arg in args:
        if arg.kwarg_only and not inserted_kw_marker:
            rendered.append("*")
            inserted_kw_marker = True
        rendered.append(f"{arg.py_name}: {arg.py_type}{format_default(arg)}")
    return ", ".join(rendered)


def call_target(spec: OpSpec) -> str:
    base = f"torch.ops.{spec.namespace}.{spec.name}"
    if spec.overload_name:
        return f"{base}.{spec.overload_name}"
    return base


def render_docstring(spec: OpSpec) -> str:
    lines = [
        '"""',
        f"Typed wrapper for ``{spec.namespace}::{spec.name}``.",
        "",
        "Torch schema::",
        "",
        f"    {spec.schema}",
    ]
    if spec.args:
        lines.extend(["", "Args:"])
        for arg in spec.args:
            notes = []
            if arg.is_write:
                notes.append("modified in-place")
            if arg.is_out:
                notes.append("out argument")
            suffix = f" ({'; '.join(notes)})" if notes else ""
            lines.append(f"    {arg.py_name}: {arg.py_type}{suffix}.")
    lines.extend(["", f"Returns: {spec.return_annotation}.", '"""'])
    return "\n".join(lines)


def render_wrapper(spec: OpSpec) -> str:
    signature = (
        f"def {spec.python_name}({format_signature_args(spec.args)}) "
        f"-> {spec.return_annotation}:"
    )
    call_args = ", ".join(arg.py_name for arg in spec.args)
    body = f"{call_target(spec)}({call_args})"
    if spec.return_annotation != "None":
        body = f"return {body}"
    return "\n".join(
        [
            signature,
            indent(render_docstring(spec), "    "),
            "    _require_native()",
            indent(body, "    "),
        ]
    )


def fake_return_expression(spec: OpSpec) -> str:
    if not spec.returns:
        return "pass"

    qualified_name = f"{spec.namespace}::{spec.name}"
    shape_rule = FAKE_TENSOR_SHAPE_RULES.get(qualified_name)
    if shape_rule is not None:
        if len(spec.returns) != 1 or spec.returns[0].py_type != "torch.Tensor":
            raise ValueError(
                f"Fake shape rule for {qualified_name} requires one Tensor return"
            )
        arg_names = {arg.py_name for arg in spec.args}
        if shape_rule.like_arg not in arg_names:
            raise ValueError(
                f"Fake shape rule for {qualified_name} references missing "
                f"argument {shape_rule.like_arg!r}"
            )
        return (
            f"return {shape_rule.like_arg}.new_empty("
            f"{shape_rule.shape_expression})"
        )

    tensor_arg = next(
        (arg for arg in spec.args if arg.py_type == "torch.Tensor"), None
    )
    tensor_list_arg = next(
        (arg for arg in spec.args if arg.py_type == "list[torch.Tensor]"), None
    )
    tensor_nested_arg = next(
        (arg for arg in spec.args if arg.py_type == "list[list[torch.Tensor]]"),
        None,
    )

    if len(spec.returns) == 1:
        ret_type = spec.returns[0].py_type
        if ret_type == "torch.Tensor" and tensor_arg is not None:
            return f"return torch.empty_like({tensor_arg.py_name})"
        if ret_type == "list[torch.Tensor]" and tensor_list_arg is not None:
            return f"return [torch.empty_like(x) for x in {tensor_list_arg.py_name}]"
        if (
            ret_type == "list[list[torch.Tensor]]"
            and tensor_nested_arg is not None
        ):
            return (
                f"return [[torch.empty_like(x) for x in row] "
                f"for row in {tensor_nested_arg.py_name}]"
            )
        return "return None  # type: ignore[return-value]"

    return "return tuple(None for _ in range(" + str(len(spec.returns)) + "))"


def safe_fake_name(spec: OpSpec) -> str:
    suffix = spec.python_name.replace("_", "__")
    return f"_fake_{spec.namespace}_{suffix}"


def render_fake(spec: OpSpec) -> str:
    signature = (
        f"def {safe_fake_name(spec)}({format_signature_args(spec.args)}) "
        f"-> {spec.return_annotation}:"
    )
    return "\n".join(
        [
            f'@torch.library.register_fake("{spec.namespace}::{spec.name}")',
            signature,
            indent(fake_return_expression(spec), "    "),
        ]
    )


def namespace_module_name(namespace: str) -> str:
    if not namespace.startswith("fhelium_"):
        return namespace
    return namespace.removeprefix("fhelium_")


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file():
        existing = path.read_text(encoding="utf-8")
        if generated_content_matches(existing, content):
            return
    path.write_text(content, encoding="utf-8")


def python_semantics(content: str) -> str:
    """Return a formatting-independent representation of generated Python."""

    return ast.dump(ast.parse(content), include_attributes=False)


def generated_content_matches(actual: str, expected: str) -> bool:
    """Compare generated semantics while enforcing generator ownership."""

    actual_first_line = actual.partition("\n")[0]
    expected_first_line = expected.partition("\n")[0]
    return actual_first_line == expected_first_line and python_semantics(
        actual
    ) == python_semantics(expected)


def render_namespace_module(namespace: str, specs: list[OpSpec]) -> str:
    needs_any = specs_need_any(specs)
    body = "\n\n\n".join(render_wrapper(spec) for spec in specs)
    return f"{render_header(needs_any, require_native=True)}\n\n{body}\n"


def specs_need_any(specs: Iterable[OpSpec]) -> bool:
    for spec in specs:
        if any(arg.py_type == "Any" for arg in spec.args):
            return True
        if any(ret.py_type == "Any" for ret in spec.returns):
            return True
    return False


def render_header(needs_any: bool, *, require_native: bool) -> str:
    typing_import = "from typing import Any\n" if needs_any else ""
    native_guard = (
        "def _require_native() -> None:\n"
        "    from fhelium.native import require_native\n\n"
        "    require_native()"
        if require_native
        else ""
    )
    return HEADER_TEMPLATE.format(
        generated_marker=GENERATED_MARKER,
        typing_import=typing_import,
        native_guard=native_guard,
    )


def render_init(specs_by_namespace: dict[str, list[OpSpec]]) -> str:
    lines = [
        GENERATED_MARKER,
        "# Do not edit!",
        "",
    ]
    all_names: list[str] = []
    for namespace, specs in specs_by_namespace.items():
        module = namespace_module_name(namespace)
        names = [spec.python_name for spec in specs]
        all_names.extend(names)
        lines.append(f"from .{module} import {', '.join(names)}")
    lines.extend(["", "__all__ = ["])
    lines.extend(f"    {name!r}," for name in sorted(all_names))
    lines.append("]")
    return "\n".join(lines) + "\n"


def render_fake_module(specs_by_namespace: dict[str, list[OpSpec]]) -> str:
    all_specs = [
        spec for specs in specs_by_namespace.values() for spec in specs
    ]
    fake_ops = [
        render_fake(spec)
        for specs in specs_by_namespace.values()
        for spec in specs
    ]
    return (
        f"{render_header(specs_need_any(all_specs), require_native=False)}\n\n"
        + "\n\n\n".join(fake_ops)
        + "\n"
    )


def write_generated(
    specs_by_namespace: dict[str, list[OpSpec]], output_dir: Path
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    expected_files = {
        "__init__.py",
        "fake_op.py",
        *(
            f"{namespace_module_name(namespace)}.py"
            for namespace in specs_by_namespace
        ),
    }
    for path in output_dir.glob("*.py"):
        if path.name in expected_files:
            continue
        content = path.read_text(encoding="utf-8")
        if content.startswith(GENERATED_MARKER):
            path.unlink()
    for namespace, specs in specs_by_namespace.items():
        module = namespace_module_name(namespace)
        write_if_changed(
            output_dir / f"{module}.py",
            render_namespace_module(namespace, specs),
        )
    write_if_changed(
        output_dir / "__init__.py", render_init(specs_by_namespace)
    )
    write_if_changed(
        output_dir / "fake_op.py", render_fake_module(specs_by_namespace)
    )


def format_generated(output_dir: Path) -> None:
    ruff = shutil.which("ruff")
    if ruff is None:
        return
    subprocess.run([ruff, "format", str(output_dir)], check=True)


def diff_dirs(expected_dir: Path, actual_dir: Path) -> str:
    messages: list[str] = []
    expected_files = sorted(path.name for path in expected_dir.glob("*.py"))
    actual_files = sorted(
        path.name
        for path in actual_dir.glob("*.py")
        if path.name in expected_files
    )
    missing = sorted(set(expected_files) - set(actual_files))
    if missing:
        messages.append(
            "Generated wrapper files are missing from the output directory:\n"
            f"  missing: {missing}"
        )
    for name in sorted(set(expected_files) & set(actual_files)):
        expected_content = (expected_dir / name).read_text(encoding="utf-8")
        actual_content = (actual_dir / name).read_text(encoding="utf-8")
        if not generated_content_matches(actual_content, expected_content):
            messages.append(
                "".join(
                    difflib.unified_diff(
                        actual_content.splitlines(keepends=True),
                        expected_content.splitlines(keepends=True),
                        fromfile=str(actual_dir / name),
                        tofile=str(expected_dir / name),
                    )
                )
            )
    return "\n".join(messages)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate typed Python wrappers for FHElium custom Torch ops."
    )
    parser.add_argument(
        "--path",
        type=Path,
        default=Path("fhelium/native/torchops"),
        help="Directory containing compiled custom op .so files.",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("fhelium/native/wrapper"),
        help="Directory for generated Python wrapper files.",
    )
    parser.add_argument(
        "--namespace-prefix",
        default="fhelium_",
        help="Only generate wrappers for dispatcher namespaces with this prefix.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Generate into a temporary directory and fail if committed wrappers differ.",
    )
    parser.add_argument(
        "--no-format",
        action="store_true",
        help="Do not format generated files when Ruff is available (generation only).",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print loaded libraries and discovered schemas.",
    )
    return parser.parse_args()


def generate(args: argparse.Namespace) -> dict[str, list[OpSpec]]:
    load_libraries(args.path.resolve(), verbose=args.verbose)
    specs = collect_specs(args.namespace_prefix)
    if not specs:
        raise RuntimeError(
            f"No custom op schemas found for namespace prefix {args.namespace_prefix!r}"
        )
    validate_specs(specs)
    if args.verbose:
        for namespace, namespace_specs in specs.items():
            print(f"\nNamespace: {namespace}")
            for spec in namespace_specs:
                print(f"  {spec.schema}")
    return specs


def main() -> None:
    args = parse_args()
    specs = generate(args)
    if args.check:
        with tempfile.TemporaryDirectory(
            prefix="fhelium-native-wrapper-check-"
        ) as tmp:
            tmp_path = Path(tmp)
            write_generated(specs, tmp_path)
            if not args.no_format:
                format_generated(tmp_path)
            diff = diff_dirs(tmp_path, args.output)
            if diff:
                print(diff)
                raise SystemExit(1)
        return
    write_generated(specs, args.output)
    if not args.no_format:
        format_generated(args.output)
    print(
        f"Generated wrappers for {sum(len(v) for v in specs.values())} ops in {args.output}"
    )


if __name__ == "__main__":
    main()
